#!/bin/sh

# Linux Kernel Development Setup

# Ncurses Header Files
apk add ncurses-dev
# Flex
apk add flex
# GNU Bison
apk add bison
# Linux Header Files
apk add linux-headers
# GNU Diff Utilities
apk add diffutils
# Elf Utils Header Files
apk add elfutils-dev
# Cpio Archiving Utility (useful for initramfs)
apk add cpio cpio-doc
# Findutils (adds the GNU find command, needed for kernel build)
apk add findutils
# OpenSSL dev
apk add openssl-dev
# Syslinux Bootloader
apk add syslinux syslinux-doc
# cdrkit (for ISO image generation)
apk add cdrkit cdrkit-doc
