#!/bin/sh

# Man
apk add man-db man-db-doc
# Sudo
apk add sudo
# Sway Man Pages
apk add sway-doc
# Vim
apk add vim
# Git
apk add git
# Foot Man Pages (The default Sway terminal)
apk add foot-doc
# Sway Background (Fix blank background)
apk add swaybg
# OpenSSH Client (Adds commands like ssh-keygen for example)
apk add openssh-client
# QEMU with GTK UI (PC Emulator)
apk add qemu-system-x86_64 qemu-doc qemu-ui-gtk
# QEMU img utility
apk add qemu-img
# GNU Bash
apk add bash bash-doc
# GNU Coreutils
apk add coreutils coreutils-doc
# GNU Texinfo (adds the info command to read GNU documentation)
apk add texinfo
