#!/bin/sh

# Meson Build System
apk add meson
# Wayland
apk add wayland-dev
# Wayland Protocols
apk add wayland-protocols-dev
# libdrm (user mode interface to kernel DRM system)
apk add libdrm-dev
# libxkbcommon (keyboard handling library)
apk add libxkbcommon-dev
# Pixman (pixel manipulation library)
apk add pixman-dev
# hwdata
apk add hwdata-dev
# libdisplay-info
apk add libdisplay-info-dev
# eudev
apk add eudev-dev
# libseat (seat management library)
apk add libseat-dev
# libinput (handle input devices)
apk add libinput-dev
